export const tableData = [
    {
        sLNo: "1",
        assignmentTitle: "Test 1 ",
        dates: "2023/08/9",
        submittedOn: "20223/09/09",
        noOfsubstitute: "09",
        inventoryStatus: "Pending",
        asignee: "GUSD",
        remark: "-",
        action: "",
    },
    {
        sLNo: "2",
        assignmentTitle: "Test 2",
        dates: "2023/08/9",
        submittedOn: "20223/09/09",
        noOfsubstitute: "90",
        inventoryStatus: "Rejected",
        asignee: "GUSD",
        remark: "-",
        action: "",
    },
    {
        sLNo: "2",
        assignmentTitle: "Test 2",
        dates: "2023/08/9",
        submittedOn: "20223/09/09",
        noOfsubstitute: "90",
        inventoryStatus: "Submitted",
        asignee: "GUSD",
        remark: "-",
        action: "",
    },
    {
        sLNo: "2",
        assignmentTitle: "Test 2",
        dates: "2023/08/9",
        submittedOn: "20223/09/09",
        noOfsubstitute: "90",
        inventoryStatus: "Reviewed & Resubmitted",
        asignee: "GUSD",
        remark: "-",
        action: "",
    },
    {
        sLNo: "2",
        assignmentTitle: "Test 2",
        dates: "2023/08/9",
        submittedOn: "20223/09/09",
        noOfsubstitute: "90",
        inventoryStatus: "Approved",
        asignee: "GUSD",
        remark: "-",
        action: "",
    },
    {
        sLNo: "2",
        assignmentTitle: "Test 2",
        dates: "2023/08/9",
        submittedOn: "20223/09/09",
        noOfsubstitute: "90",
        inventoryStatus: "Rejected",
        asignee: "GUSD",
        remark: "-",
        action: "",
    },
    {
        sLNo: "2",
        assignmentTitle: "Test 2",
        dates: "2023/08/9",
        submittedOn: "20223/09/09",
        noOfsubstitute: "90",
        inventoryStatus: "Submitted",
        asignee: "GUSD",
        remark: "-",
        action: "",
    },
    {
        sLNo: "2",
        assignmentTitle: "Test 2",
        dates: "2023/08/9",
        submittedOn: "20223/09/09",
        noOfsubstitute: "90",
        inventoryStatus: "Reviewed & Resubmitted",
        asignee: "GUSD",
        remark: "-",
        action: "",
    },
    {
        sLNo: "2",
        assignmentTitle: "Test 2",
        dates: "2023/08/9",
        submittedOn: "20223/09/09",
        noOfsubstitute: "90",
        inventoryStatus: "Approved",
        asignee: "GUSD",
        remark: "-",
        action: "",
    },
];